### ISSUE TITLE
Write and send mail form

### ISSUE THREAD

**Issue by wolkemann** [wolkemann/capstone-project#1]
## Value Preposition

As a User I need a form to send a mail

## Description

![issue1](https://user-images.githubusercontent.com/74557154/159948711-4f168a78-4d45-4ba2-a8be-4b2a460c2154.png)

## Acceptance Criteria

- [x] The textarea can contain only a maximum amout of characters
- [x]  The text can only be plain text and cannot contain html tags
- [x]  The current amount of characters that can be used must be visible so the user knows how much he can still write.
- [x] For every state of the sending request (pending..., successful..., error...) there should be a message in the UI to help the User.

## Tasks

- [x]  Create the single components
    - [x]  textarea
    - [x]  send button
- [x]  Implement the logic so that posted data is saved in the database
- [x]  implement the logic so that the current avaiable characters is displayed
