### ISSUE TITLE
Account creation success messagge

### ISSUE THREAD

**Issue by wolkemann** [wolkemann/capstone-project#13]
## Value Preposition

As a User I want a messagge that tells me what to do after I have create an account for the first time.

## Description

![issue4](https://user-images.githubusercontent.com/74557154/160836355-858c6f7e-f654-4375-ba96-b6237ef51d89.png)

## Acceptance Criteria

- [x] After the user is registered and the random nickname is assigned, a success page should hint the user what to do next.

## Tasks

- [x] Create the account creation success page
- [x] Create the "write your first letter" button
- [x] Create the "go to your dashboard" button
