### ISSUE TITLE
Inbox scrolling

### ISSUE THREAD

**Issue by wolkemann** [wolkemann/capstone-project#16]
## Value Preposition

As a User I want to browse the letters that I received so I can choose to which send a reply.

## Description

![issue5](https://user-images.githubusercontent.com/74557154/161032505-71445e3a-f170-48b7-8221-63640fc0e7c2.png)

## Acceptance Criteria

- [x] The user can scroll horizontally to browse the letters.

## Tasks

- [x] Create the Inbox page component
- [x] Fetch the letters from the database for the corresponding user
