### ISSUE TITLE
Reply button

### ISSUE THREAD

**Issue by wolkemann** [wolkemann/capstone-project#17]
## Value Preposition

As I user I want a reply button so I can reply to a selected mail.

## Description

![issue6](https://user-images.githubusercontent.com/74557154/161222094-0b9acc48-5871-4ab9-aa4f-905bce80717e.png)

## Acceptance Criteria

- [x] The user can click to the corrisponding click button and he's redirected to a form where he can reply.

## Tasks

- [x] fetch the mail id to link the reply mail
- [x] create the reply mail page
