### ISSUE TITLE
Stickers page > Recently Received Stickers

### ISSUE THREAD

**Issue by wolkemann** [wolkemann/capstone-project#21]
## Value Preposition

As a User I want to be able to see the recently obtained stickers.

## Description

When the Users goes to the stickers page a window with the last 5 Stickers received is displayed

## Acceptance Criteria

- [x] The displayed Stickers should be only the last 5.

## Tasks

- [x] fetch the correct data from the api
- [x] create the section "Recently obtained Stickers" inside the Sticker Page
