### ISSUE TITLE
Sticker button and popupwindow

### ISSUE THREAD

**Issue by wolkemann** [wolkemann/capstone-project#26]
## Value Preposition

As a User I want a button that shows a popup where I can choose a Sticker to send.

## Description

When the User pushes the button  a popup is shown that contains the Stickers

## Acceptance Criteria

- [x] the popup is always at the center of the app.

## Tasks

- [x] Create the popup window component
- [x]  Implement the logic in the button
