### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by wolkemann** [wolkemann/capstone-project#3]
## Value Preposition

As a User I need a navigation menu so that i can move easly between the App's pages.

## Description

![issue2](https://user-images.githubusercontent.com/74557154/160113694-a58a8fe8-a333-4ea5-b30b-9f4ed9ffbee8.png)

## Acceptance Criteria

- [x] The user can navigate through the App using the Navigation Bar component

## Tasks

- [x] Create the Navigation Bar component
- [x] Create the Navigation button component
- [x] Link the icon to corresponding App sections.
