### ISSUE TITLE
Sticker selection

### ISSUE THREAD

**Issue by wolkemann** [wolkemann/capstone-project#30]
## Value Preposition

As a User I want that the sticker that I have selected is highlighted in some way.

## Description

When the User clicks on the selected sticker, this one changes the background to indicate that it is selected.

## Acceptance Criteria

- [x] When the sticker is clicked, it is highlighted.
- [x] When the user clicks an already selected sticker, this one is deselected.
- [x] Only one sticker can be choosen

## Tasks

- [x] Create the Sticker component
- [x] Implement the logic
