### ISSUE TITLE
Stickers page > Stickers Collection

### ISSUE THREAD

**Issue by wolkemann** [wolkemann/capstone-project#34]
## Value Preposition

As a User I want to see my stickers collection to see how many feedbacks/appricientions I received.

## Description

When the Users goes to the stickers page a collection of obtained stickers is shown. Each type of sticker will have a counter to show how many of that type the User has.

## Acceptance Criteria

- [x] Only the obtained stickers are shown, if still not obtained then there will be a placeholder.

## Tasks

- [x] implement a custom Hook to build a counter for every sticker
- [x] create the Stickers Collection section

**Comment by dohoeppner** [comment]
Just a feedback for the "Value Preposition": I would maybe add the real value for the user ("so that..." / "to be able to...") to see the personal stickers collection. Like, what is the idea behind the stickers? To feel better? Or to get a nice feedback of others? Or both? Whatever, you will know the best :)

**Comment by wolkemann** [comment]
> Just a feedback for the "Value Preposition": I would maybe add the real value for the user ("so that..." / "to be able to...") to see the personal stickers collection. Like, what is the idea behind the stickers? To feel better? Or to get a nice feedback of others? Or both? Whatever, you will know the best :)

Good advice, I wrote this User Story too quickly!
