### ISSUE TITLE
Inbox page > Show a message when empty

### ISSUE THREAD

**Issue by wolkemann** [wolkemann/capstone-project#40]
## Value Preposition

As a User I want to see a message that tells me my Inbox is empty so that I know there are no replies to send sticker to.

## Description

When the User goes to the Inbox page and there no replies, a message is displayed that tells the user that there are no replies.

## Acceptance Criteria

- [ ] The message should appear only when the inbox is empty

## Tasks

- [ ] fetch the correct data from the api
- [ ] create the HTML structure.
