### ISSUE TITLE
Reply page > Show a message when empty

### ISSUE THREAD

**Issue by wolkemann** [wolkemann/capstone-project#41]
## Value Preposition

As a User I want to see a message that tells me my Reply section is empty so that I know there are no letters to reply to.

## Description

When the User goes to the Reply page and there no letters, a message is displayed that tells the user that there are no replies.

## Acceptance Criteria

- [ ] The message should appear only when the Reply section is empty

## Tasks

- [ ] fetch the correct data from the api
- [ ] create the HTML structure.
