### ISSUE TITLE
Send Reply > Sending successful notification

### ISSUE THREAD

**Issue by wolkemann** [wolkemann/capstone-project#42]
## Value Preposition

As a User I want to see a notification that tells me that my reply was successfully sent so that I know the sending operation went well.

## Description

When the User sends a reply a message is shown that tells the sending status (pending, error, success).

## Acceptance Criteria

- [ ] The message should appear when the data are sent.

## Tasks

- [ ] create the logic
- [ ] create the HTML structure.
