### ISSUE TITLE
Create an Account

### ISSUE THREAD

**Issue by wolkemann** [wolkemann/capstone-project#8]
## Value Preposition

As a User I want to register myself easly using my google or github account.

## Description

![issue3](https://user-images.githubusercontent.com/74557154/160813465-6209c297-229d-4306-b51e-eb6de71857ae.png)

## Acceptance Criteria

- [x] The user must choose one provider.
- [x] When the user registers for the firs time a random nickname si generated and assigned.

## Tasks

- [x] Create the register page
- [x] Create the register page single component
- [x] Generate a random nickname that is used in place of the real name.
- [x] Implement the backend logic.
